### ISSUE TITLE
Add Solana Wallet Adapters and basic web3 functionality

### ISSUE THREAD

**Issue by andrii1990123** [andrii1990123/arcarde2earn#1]
Reference: https://github.com/solana-labs/dapp-scaffold/tree/main/src

We have two tokens in Solana DevNet that can be tested with

```
export let ARCADE_ADDRESS_MINT = new PublicKey(
  "tToKcFtUUQvDqSWbqpEhvgXwTMzWNx7mDpvxKLALrkY"
);

export let XARCADE_ADDRESS_MINT = new PublicKey(
  "tXToFAXN4PzPKyWKgeCfeRYcsUN1MgVH7hk6fxq4oXb"
);
```

The hope would be to add the following which references (https://github.com/ArcadeDevelopment/platform_dapp/tree/main/src/hooks)

```
const ARCADE = useUserBalance(ARCADE_ADDRESS_MINT);
const XARCADE = useUserBalance(XARCADE_ADDRESS_MINT);
const ARCADE_SUPPLY = useTokenSupply(ARCADE_ADDRESS_MINT);
const XARCADE_SUPPLY = useTokenSupply(XARCADE_ADDRESS_MINT);
```

From here, we can update the "Wallet" card on the home screen as well as change the "Bonus Pool Rankings" to Token Supply information.

**Comment by andrii1990123** [comment]
the above tokens (tToK and tXTo) are both on devnet:
https://solscan.io/token/tToKcFtUUQvDqSWbqpEhvgXwTMzWNx7mDpvxKLALrkY?cluster=devnet

These are in use for testing purposes for now, so they don't have metadata information in Phantom wallet

**Comment by aksharth** [comment]
pushed code with this just need tXTo token to add there address
