### ISSUE TITLE
Replace "Mission Pools" slider with "Games" - New Flow

### ISSUE THREAD

**Issue by andrii1990123** [andrii1990123/arcarde2earn#13]
As we're looking to have many games in the future and, with each game, many missions, it may be needed to change "Mission Pool" slider to being "Games" slider.

![image](https://user-images.githubusercontent.com/893684/158697512-2ba3ee79-b665-4d3f-9d6d-7c015b4a942a.png)

I'm not sure how I want the next page to be, so just leave this for now, i'll update this issue with my idea for the next part.

**Comment by andrii1990123** [comment]
> As we're looking to have many games in the future and, with each game, many missions, it may be needed to change "Mission Pool" slider to being "Games" slider.
> 
> ![image](https://user-images.githubusercontent.com/893684/158697512-2ba3ee79-b665-4d3f-9d6d-7c015b4a942a.png)
> 
> I'm not sure how I want the next page to be, so just leave this for now, i'll update this issue with my idea for the next part.

**Comment by aksharth** [comment]
with static data done
