### ISSUE TITLE
i18n support 

### ISSUE THREAD

**Issue by andrii1990123** [andrii1990123/arcarde2earn#4]
Not a requirement at the present moment, but we will be looking into internationalize the strings of the dapp to be able to provide community-translated support. I'm just putting this task here just for overview.

**Comment by aksharth** [comment]
community-translated support example can you give?
Do we have to implement this?

**Comment by andrii1990123** [comment]
We'll want to implement the i18n support. I gave you read access to this repo:
https://github.com/andrii1990123/i18n-translations

The basic idea is that we're going to want to build a way to parse these translation.json files and replace all strings with their translation.
https://react.i18next.com/ gives a bit of documentation on the matter, but I'll probably start building out an example in the next few days. We're going to have about 10 different languages, so we'll want to be able to detect what locale language a user has, and then load the translation for that user. An example would be, as you're from Indonesia, we'd want to detect your locale's native language, load the Indonesian's translation.json, and allow the user to toggle if they wish to load English instead (or another language).
