### ISSUE TITLE
center sponsors-images on MissionItem

### ISSUE THREAD

**Issue by andrii1990123** [andrii1990123/arcarde2earn#7]
![image](https://user-images.githubusercontent.com/893684/154976542-eb5d9956-309b-431a-bf3b-1cc633d04131.png)

Internally, we're going to limit our sponsors to a max of 2 per mission. So I think if we can, lets center the images so that they feel more equal distance apart and padded similarly.

Text-Align: center ALMOST gets us there, but it still doesn't look quite right:
![image](https://user-images.githubusercontent.com/893684/154977148-6b4f424d-3681-4972-ba93-9292785447ac.png)

Any ideas?

**Comment by aksharth** [comment]
i done that on my side if some position need to fix then we can do 
also lets merge code as onling I can see many progress that can be conflict

**Comment by andrii1990123** [comment]
Please push code before close the issue(task).

I will reopen this again.
First, push your updates to git and after that update the issue(task) tab in git.
