### ISSUE TITLE
Concept idea for Wallet

### ISSUE THREAD

**Issue by andrii1990123** [andrii1990123/arcarde2earn#8]
We're currently exploring an idea where we remove the dashboard all together and instead move the "Wallet" widget and "Rewards" to a "sidebar" or modal. 

An example would be similar to zed.run:
![image](https://user-images.githubusercontent.com/893684/155420203-548d9acd-9c5f-4633-9c44-8b33db4be3fd.png)

A concept visualization of this would be:
![image](https://user-images.githubusercontent.com/893684/155421628-11fa894e-2350-429f-8ebe-df285c818cc3.png)

**Comment by aksharth** [comment]
so we start working on this design change? 
we have to create https://image.prntscr.com/image/ajXgmN4qS72U0hmfclQdCA.png
this type design in side way or in popup ?

**Comment by aksharth** [comment]
we designed same side way , just need to approve design

**Comment by andrii1990123** [comment]
Changes recommended thus far:

- Remove the TopUp and Transfer buttons. We may use this in the future for the "Buy Arcade with FTX Pay" but we're still working on that collaboration.
- Change "Transfers" to "Pending Rewards", this will be where we will have the aggregation of our rewards as well as list out the missions that those rewards came from
- Add a collapsible section for "My Missions" which will be where we can list out the missions that the user is currently enlisted in.
